### PR TITLE
Updating Radar Icon + Fix macOS Build Error

### PR DESCRIPTION
**Pull request by ShikiSuen**
Credits: Shiki Suen (2020)

### CODE REVIEW

**Comment by ShikiSuen** [comment]
Current packaging script fails on macOS Catalina. Hence a little fix.

**Comment by GraionDilach** [comment]
Please reject this PR. This PR is part of a hostile attempt to break artwork integrity.

**Comment by ShikiSuen** [comment]
@GraionDilach 
No. My hostility is always to your entire Attack Superior community.

**Comment by ShikiSuen** [comment]
@GraionDilach 

Okay, real comments:

Yours are good design, but not suitable for radar (better be in the menu of "new campaign" or the game pause menu, etc.). Too much visual disturbance. I personally admire your tenacity on following the aesthetics of EA original RA2 UI. However, EA learnt some lessons hence their decisions made radar icons simpler in RA3.

**Comment by cookgreen** [comment]
Your design is good, but please remember this is RA2 not RA3
Thanks for your PR

**Comment by ShikiSuen** [comment]
@cookgreen Thanks for your response.
I guess you might want to sync some fixes from OpenRA/ra2 , including the too frequent low-power notice, etc.

**Comment by ShikiSuen** [comment]
@cookgreen Here's how to fix it. (by @Mailaender )
image

**Comment by cookgreen** [comment]
Awesome!

**Pull request closed without merging**
